import Head from 'next/head'
import Layout from './components/Layout'

export default function Home() {
  return (
    
    <>
      <Head>
        <title>Content-WatchDog</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <main className='flex items-center text-white w-full min-h-screen'>
        <Layout>
          <div className='flex items-center justify-center w-full  font-bold '>
            <span className='text-8xl'> Content-Watch-Dog</span>
          </div>
        </Layout>
      </main>

    </>
  )
}
