import Head from 'next/head'
import Layout from './components/Layout'

export default function Home() {
  return (
    
    <>
      <Head>
        <title>Content-WatchDog</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <main className='flex items-center text-white w-full min-h-screen'>
        <Layout>
          <div className='text-center text-8xl'>
            <span class='title-word title-word-1'>Content</span>
            <span class='title-word title-word-2'>WatchDog</span>
          </div>
        </Layout>
      </main>

    </>
  )
}
